server:
  port: 8223

logging:
  level:
    org.springframework: debug
    web: debug


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update

    showSql: true
    jwt:
      secret: asdqwqwe123123


  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    log-request-details: true
